services:
  web:
    build: ./app
    networks:
      testing-tor-docker-compose_tor-network:
        ipv4_address: 10.5.8.23  # Статический IP-адрес
    expose:
      - "5000"  # Проброс портов

networks:
  testing-tor-docker-compose_tor-network:
    driver: bridge
    external: true  # Указываем, что сеть уже существует